/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export interface AnnouncementInfo {
  id?: number;
  sortOrder?: number;
  title?: string;
  content?: string;
  linkUrl?: string;
  linkLabel?: string;
  afterServiceEvent?: boolean;
  displayStartDate?: string;
  displayEndDate?: string;
}
