/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */
import type { ChurchMemberResponseGender } from './churchMemberResponseGender';

export interface ChurchMemberResponse {
  id?: number;
  name?: string;
  gender?: ChurchMemberResponseGender;
  birthDate?: string;
  phoneNumber?: string;
}
