/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type LookupChurchMemberParams = {
name: string;
birthDate: string;
/**
 * @pattern ^010-\d{4}-\d{4}$
 */
phoneNumber: string;
};
