/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type MemberProfileRegisterRequestBankName = typeof MemberProfileRegisterRequestBankName[keyof typeof MemberProfileRegisterRequestBankName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberProfileRegisterRequestBankName = {
  KB: 'KB',
  SHINHAN: 'SHINHAN',
  WOORI: 'WOORI',
  HANA: 'HANA',
  NH: 'NH',
  IBK: 'IBK',
  SC: 'SC',
  KAKAO: 'KAKAO',
  TOSS: 'TOSS',
  KBANK: 'KBANK',
  BUSAN: 'BUSAN',
  DAEGU: 'DAEGU',
  GWANGJU: 'GWANGJU',
  JEONBUK: 'JEONBUK',
  JEJU: 'JEJU',
  KYONGNAM: 'KYONGNAM',
  SUHYUP: 'SUHYUP',
  SAEMAUL: 'SAEMAUL',
  SHINHYUP: 'SHINHYUP',
  POST: 'POST',
} as const;
