/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */
import type { MemberMeResponseRole } from './memberMeResponseRole';
import type { MemberMeResponseStatus } from './memberMeResponseStatus';
import type { ProfileInfo } from './profileInfo';

export interface MemberMeResponse {
  memberId?: number;
  email?: string;
  role?: MemberMeResponseRole;
  status?: MemberMeResponseStatus;
  lastLoginAt?: string;
  profileCompleted?: boolean;
  profile?: ProfileInfo;
}
