/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type MemberSummaryResponseStatus = typeof MemberSummaryResponseStatus[keyof typeof MemberSummaryResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberSummaryResponseStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  WITHDRAWN: 'WITHDRAWN',
  BLOCKED: 'BLOCKED',
} as const;
