/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */
import type { MemberSummaryResponseRole } from './memberSummaryResponseRole';
import type { MemberSummaryResponseStatus } from './memberSummaryResponseStatus';
import type { MemberSummaryResponseDepartment } from './memberSummaryResponseDepartment';

export interface MemberSummaryResponse {
  memberId?: number;
  name?: string;
  role?: MemberSummaryResponseRole;
  status?: MemberSummaryResponseStatus;
  department?: MemberSummaryResponseDepartment;
  profileImageUrl?: string;
  profileCompleted?: boolean;
}
