/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type PlatformDetailResponseApprovalStatus = typeof PlatformDetailResponseApprovalStatus[keyof typeof PlatformDetailResponseApprovalStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlatformDetailResponseApprovalStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
