/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export interface PlatformSaveRequest {
  /**
   * @minLength 0
   * @maxLength 100
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  scheduleText?: string;
  startsAt?: string;
  endsAt?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  location?: string;
  content?: string;
  purpose?: string;
  etc?: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  posterUrl?: string;
}
