/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */
import type { PlatformMemberResponseRole } from './platformMemberResponseRole';
import type { PlatformMemberResponseStatus } from './platformMemberResponseStatus';

export interface PlatformMemberResponse {
  platformMemberId?: number;
  platformId?: number;
  memberId?: number;
  memberName?: string;
  role?: PlatformMemberResponseRole;
  status?: PlatformMemberResponseStatus;
  requestedAt?: string;
  approvedAt?: string;
  rejectedReason?: string;
}
