/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type PlatformListItemResponseClosedStatus = typeof PlatformListItemResponseClosedStatus[keyof typeof PlatformListItemResponseClosedStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlatformListItemResponseClosedStatus = {
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED',
} as const;
