/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type PlatformMemberResponseRole = typeof PlatformMemberResponseRole[keyof typeof PlatformMemberResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlatformMemberResponseRole = {
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  MEMBER: 'MEMBER',
} as const;
