/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export interface PlatformSaveRequest {
  title?: string;
  scheduleText?: string;
  startsAt?: string;
  endsAt?: string;
  location?: string;
  content?: string;
  purpose?: string;
  etc?: string;
  posterUrl?: string;
  operatingStatus?: string;
}
