/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type PlatformDetailResponseClosedStatus = typeof PlatformDetailResponseClosedStatus[keyof typeof PlatformDetailResponseClosedStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlatformDetailResponseClosedStatus = {
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED',
} as const;
