/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */
import type { ProfileInfoGender } from './profileInfoGender';
import type { ProfileInfoDepartment } from './profileInfoDepartment';
import type { ProfileInfoBankName } from './profileInfoBankName';

export interface ProfileInfo {
  name?: string;
  gender?: ProfileInfoGender;
  birthDate?: string;
  phoneNumber?: string;
  profileImageUrl?: string;
  department?: ProfileInfoDepartment;
  position?: string;
  bankName?: ProfileInfoBankName;
  accountNumber?: string;
}
