/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */
import type { WorshipBulletinRequest } from './worshipBulletinRequest';
import type { WorshipPraiseRequest } from './worshipPraiseRequest';
import type { WorshipAnnouncementRequest } from './worshipAnnouncementRequest';

export interface WorshipSaveRequest {
  /**
   * @minLength 0
   * @maxLength 150
   */
  sermonTitle: string;
  worshipAt?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  preacherName?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  verseReference?: string;
  verseText?: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  youtubeUrl?: string;
  status?: string;
  bulletins?: WorshipBulletinRequest[];
  praises?: WorshipPraiseRequest[];
  announcements?: WorshipAnnouncementRequest[];
}
