/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export type WorshipDetailResponseStatus = typeof WorshipDetailResponseStatus[keyof typeof WorshipDetailResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorshipDetailResponseStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  HIDDEN: 'HIDDEN',
} as const;
