/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 주뜨 청년부 앱 API
 * 주뜨 청년부 앱 REST API 명세
 * OpenAPI spec version: v1
 */

export interface WorshipBulletinRequest {
  sortOrder?: number;
  /**
   * @minLength 0
   * @maxLength 500
   */
  imageUrl: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  mimeType: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  fileName?: string;
}
